drop table user_taggedmovies;
drop table user_taggedmovies_timestamps;
drop table user_ratedmovies;
drop table user_ratedmovies_timestamps;
drop table Movie_tags;
drop table tags;
drop table Movie_locations;
drop table Movie_genres;
drop table Movie_directors;
drop table Movie_countries;
drop table Movie_actors;
drop table Movies;
commit;